/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.jamitlabs.alexaconnect.libraries.alexa.test;

public final class R {
  public static final class attr {
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>icon_only</td><td>2</td><td></td></tr>
     * <tr><td>standard</td><td>0</td><td></td></tr>
     * <tr><td>wide</td><td>1</td><td></td></tr>
     * </table>
     */
    public static final int buttonSize=0x7f010000;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int circleCrop=0x7f010001;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>auto</td><td>2</td><td></td></tr>
     * <tr><td>dark</td><td>0</td><td></td></tr>
     * <tr><td>light</td><td>1</td><td></td></tr>
     * </table>
     */
    public static final int colorScheme=0x7f010002;
    /**
     * <p>May be a floating point value, such as "<code>1.2</code>".
     */
    public static final int imageAspectRatio=0x7f010003;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>adjust_height</td><td>2</td><td></td></tr>
     * <tr><td>adjust_width</td><td>1</td><td></td></tr>
     * <tr><td>none</td><td>0</td><td></td></tr>
     * </table>
     */
    public static final int imageAspectRatioAdjust=0x7f010004;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int scopeUris=0x7f010005;
  }
  public static final class color {
    public static final int common_google_signin_btn_text_dark=0x7f020000;
    public static final int common_google_signin_btn_text_dark_default=0x7f020001;
    public static final int common_google_signin_btn_text_dark_disabled=0x7f020002;
    public static final int common_google_signin_btn_text_dark_focused=0x7f020003;
    public static final int common_google_signin_btn_text_dark_pressed=0x7f020004;
    public static final int common_google_signin_btn_text_light=0x7f020005;
    public static final int common_google_signin_btn_text_light_default=0x7f020006;
    public static final int common_google_signin_btn_text_light_disabled=0x7f020007;
    public static final int common_google_signin_btn_text_light_focused=0x7f020008;
    public static final int common_google_signin_btn_text_light_pressed=0x7f020009;
  }
  public static final class drawable {
    public static final int common_full_open_on_phone=0x7f030000;
    public static final int common_google_signin_btn_icon_dark=0x7f030001;
    public static final int common_google_signin_btn_icon_dark_disabled=0x7f030002;
    public static final int common_google_signin_btn_icon_dark_focused=0x7f030003;
    public static final int common_google_signin_btn_icon_dark_normal=0x7f030004;
    public static final int common_google_signin_btn_icon_dark_pressed=0x7f030005;
    public static final int common_google_signin_btn_icon_light=0x7f030006;
    public static final int common_google_signin_btn_icon_light_disabled=0x7f030007;
    public static final int common_google_signin_btn_icon_light_focused=0x7f030008;
    public static final int common_google_signin_btn_icon_light_normal=0x7f030009;
    public static final int common_google_signin_btn_icon_light_pressed=0x7f03000a;
    public static final int common_google_signin_btn_text_dark=0x7f03000b;
    public static final int common_google_signin_btn_text_dark_disabled=0x7f03000c;
    public static final int common_google_signin_btn_text_dark_focused=0x7f03000d;
    public static final int common_google_signin_btn_text_dark_normal=0x7f03000e;
    public static final int common_google_signin_btn_text_dark_pressed=0x7f03000f;
    public static final int common_google_signin_btn_text_light=0x7f030010;
    public static final int common_google_signin_btn_text_light_disabled=0x7f030011;
    public static final int common_google_signin_btn_text_light_focused=0x7f030012;
    public static final int common_google_signin_btn_text_light_normal=0x7f030013;
    public static final int common_google_signin_btn_text_light_pressed=0x7f030014;
    public static final int common_ic_googleplayservices=0x7f030015;
  }
  public static final class id {
    public static final int adjust_height=0x7f040000;
    public static final int adjust_width=0x7f040001;
    public static final int auto=0x7f040002;
    public static final int dark=0x7f040003;
    public static final int icon_only=0x7f040004;
    public static final int light=0x7f040005;
    public static final int none=0x7f040006;
    public static final int standard=0x7f040007;
    public static final int wide=0x7f040008;
  }
  public static final class integer {
    public static final int google_play_services_version=0x7f050000;
  }
  public static final class string {
    public static final int alexa_api=0x7f060000;
    public static final int alexa_api_version=0x7f060001;
    public static final int alexa_product_id=0x7f060002;
    public static final int common_google_play_services_enable_button=0x7f060003;
    public static final int common_google_play_services_enable_text=0x7f060004;
    public static final int common_google_play_services_enable_title=0x7f060005;
    public static final int common_google_play_services_install_button=0x7f060006;
    public static final int common_google_play_services_install_text_phone=0x7f060007;
    public static final int common_google_play_services_install_text_tablet=0x7f060008;
    public static final int common_google_play_services_install_title=0x7f060009;
    public static final int common_google_play_services_notification_ticker=0x7f06000a;
    public static final int common_google_play_services_unknown_issue=0x7f06000b;
    public static final int common_google_play_services_unsupported_text=0x7f06000c;
    public static final int common_google_play_services_unsupported_title=0x7f06000d;
    public static final int common_google_play_services_update_button=0x7f06000e;
    public static final int common_google_play_services_update_text=0x7f06000f;
    public static final int common_google_play_services_update_title=0x7f060010;
    public static final int common_google_play_services_updating_text=0x7f060011;
    public static final int common_google_play_services_updating_title=0x7f060012;
    public static final int common_google_play_services_wear_update_text=0x7f060013;
    public static final int common_open_on_phone=0x7f060014;
    public static final int common_signin_button_text=0x7f060015;
    public static final int common_signin_button_text_long=0x7f060016;
  }
  public static final class styleable {
    /**
     * Attributes that can be used with a LoadingImageView.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #LoadingImageView_circleCrop com.jamitlabs.alexaconnect.libraries.alexa.test:circleCrop}</code></td><td></td></tr>
     * <tr><td><code>{@link #LoadingImageView_imageAspectRatio com.jamitlabs.alexaconnect.libraries.alexa.test:imageAspectRatio}</code></td><td></td></tr>
     * <tr><td><code>{@link #LoadingImageView_imageAspectRatioAdjust com.jamitlabs.alexaconnect.libraries.alexa.test:imageAspectRatioAdjust}</code></td><td></td></tr>
     * </table>
     * @see #LoadingImageView_circleCrop
     * @see #LoadingImageView_imageAspectRatio
     * @see #LoadingImageView_imageAspectRatioAdjust
     */
    public static final int[] LoadingImageView={
        0x7f010001, 0x7f010003, 0x7f010004
      };
    /**
     * <p>This symbol is the offset where the {@link com.jamitlabs.alexaconnect.libraries.alexa.test.R.attr#circleCrop}
     * attribute's value can be found in the {@link #LoadingImageView} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.jamitlabs.alexaconnect.libraries.alexa.test:circleCrop
     */
    public static final int LoadingImageView_circleCrop=0;
    /**
     * <p>This symbol is the offset where the {@link com.jamitlabs.alexaconnect.libraries.alexa.test.R.attr#imageAspectRatio}
     * attribute's value can be found in the {@link #LoadingImageView} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name com.jamitlabs.alexaconnect.libraries.alexa.test:imageAspectRatio
     */
    public static final int LoadingImageView_imageAspectRatio=1;
    /**
     * <p>This symbol is the offset where the {@link com.jamitlabs.alexaconnect.libraries.alexa.test.R.attr#imageAspectRatioAdjust}
     * attribute's value can be found in the {@link #LoadingImageView} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>adjust_height</td><td>2</td><td></td></tr>
     * <tr><td>adjust_width</td><td>1</td><td></td></tr>
     * <tr><td>none</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name com.jamitlabs.alexaconnect.libraries.alexa.test:imageAspectRatioAdjust
     */
    public static final int LoadingImageView_imageAspectRatioAdjust=2;
    /**
     * Attributes that can be used with a SignInButton.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #SignInButton_buttonSize com.jamitlabs.alexaconnect.libraries.alexa.test:buttonSize}</code></td><td></td></tr>
     * <tr><td><code>{@link #SignInButton_colorScheme com.jamitlabs.alexaconnect.libraries.alexa.test:colorScheme}</code></td><td></td></tr>
     * <tr><td><code>{@link #SignInButton_scopeUris com.jamitlabs.alexaconnect.libraries.alexa.test:scopeUris}</code></td><td></td></tr>
     * </table>
     * @see #SignInButton_buttonSize
     * @see #SignInButton_colorScheme
     * @see #SignInButton_scopeUris
     */
    public static final int[] SignInButton={
        0x7f010000, 0x7f010002, 0x7f010005
      };
    /**
     * <p>This symbol is the offset where the {@link com.jamitlabs.alexaconnect.libraries.alexa.test.R.attr#buttonSize}
     * attribute's value can be found in the {@link #SignInButton} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>icon_only</td><td>2</td><td></td></tr>
     * <tr><td>standard</td><td>0</td><td></td></tr>
     * <tr><td>wide</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name com.jamitlabs.alexaconnect.libraries.alexa.test:buttonSize
     */
    public static final int SignInButton_buttonSize=0;
    /**
     * <p>This symbol is the offset where the {@link com.jamitlabs.alexaconnect.libraries.alexa.test.R.attr#colorScheme}
     * attribute's value can be found in the {@link #SignInButton} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>auto</td><td>2</td><td></td></tr>
     * <tr><td>dark</td><td>0</td><td></td></tr>
     * <tr><td>light</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name com.jamitlabs.alexaconnect.libraries.alexa.test:colorScheme
     */
    public static final int SignInButton_colorScheme=1;
    /**
     * <p>This symbol is the offset where the {@link com.jamitlabs.alexaconnect.libraries.alexa.test.R.attr#scopeUris}
     * attribute's value can be found in the {@link #SignInButton} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.jamitlabs.alexaconnect.libraries.alexa.test:scopeUris
     */
    public static final int SignInButton_scopeUris=2;
  }
}